services:
  api:
    build: ./api-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - etl
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:pass@postgres:5432/clinical_data
      - ETL_SERVICE_URL=http://etl:8000
      - DEVELOPMENT=false
    volumes:
      - ./data:/data
    restart: unless-stopped
  
  etl:
    build: ./etl-service  
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - spark-master
    environment:
      - PYTHONPATH=/app/src:$PYTHONPATH
      - DATABASE_URL=postgresql://user:pass@postgres:5432/clinical_data
      - SPARK_MASTER_URL=spark://spark-master:7077
      - DEVELOPMENT=true
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./data:/data
      - ./etl-service:/app  # Mount your ETL scripts to Spark containers
    working_dir: /app
    command: ["uvicorn","src.main:app","--host","0.0.0.0","--port","8000"]
    restart: unless-stopped
  
  postgres:
    image: public.ecr.aws/docker/library/postgres:15
    environment:
      - POSTGRES_DB=clinical_data
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    tmpfs:
      - /var/lib/postgresql/data:noexec,nosuid,size=512m
    restart: unless-stopped

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "7077:7077" # Spark master port
      - "8080:8080" # Spark master web UI
    volumes:
      - ./data:/data
      - ./etl-service:/app  # Mount ETL scripts
    restart: unless-stopped

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081" # Spark worker web UI
    volumes:
      - ./data:/data
      - ./etl-service:/app  # Mount ETL scripts
    restart: unless-stopped

